### ISSUE TITLE
Rethink retry mechanism

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/ays9#267] opened 2017-09-20 10:14 UTC
## Current Situation
Currently when the execution of a run fails, the run is marked as errored and a level of error is link with it.  The run scheduler will automatically retry to execute the same run until it reach the error level 6.
 Each try is delayed a bit more. See: https://github.com/Jumpscale/ays9/blob/e7947c2a2a4702a57cca2bdc1f191aa396f5156d/JumpScale9AYS/ays/lib/RunScheduler.py#L7-L15

## Problems
I see multiple problems with this design:
- No way to configure this delay for each error level, 
  would that be per run, per AYS repository or globally.
- In some situation, a AYS user can execute a blueprint and want to wait for all retries to be done before deciding if its requests has failed or not.
In this scenario, we force the use to wait for up to 46 minutes. I don't think this number is reasonable.
- The only ways to know if a run is done is or to poll for the run detail, or to use the callback feature. 
Both present some problems.
  - Poll: 
    - This is not efficient and create a lot of "useless" request to AYS
    - There is not way to know if the run is going to be retried again or not
  - Callback:
    - This force the caller to block until the callback is done, which can lead to deadlock if for some reason ays stops sending callback
       - In case of the orchestrator, this means we block on an HTTP request, which block a connection. If case orchestrator has a lot of request, we can easily reach max number of file descriptor
    - There is not way to know if the run is going to be retried again or not
    - Each try sends a callback, caller doesn't know after how many callback it should stop blocking.

## Some idea how to improve situations:
- Make retry delay configurable. Per AYS repo or globablly
- Allow user to specify the retry delays when executing a run ?
- Allow user to specify if he wants to receive a callback for each tries, only in case of success, only X tries, specify a timeout

**Comment by rkhamis** [comment] 2017-09-20 10:34
How about that we do in the callback data, how many retries are left, and when the next one is to be retired. We can then wait for that time and re-block in some way?

**Comment by rkhamis** [comment] 2017-09-20 10:36
I think global configurations, in general, are the way to go. Too many configuration options get confusing and add complexity to users.

+1 for configurable

**Comment by zaibon** [comment] 2017-09-20 10:38
> How about that we do in the callback data, how many retries are left, and when the next one is to be retired. We can then wait for that time and re-block in some way?

I like that cause then the caller has all the knowledge he needs to take decision on what to do.

**Comment by rkhamis** [comment] 2017-10-11 08:52
It should be configurable per actor (with default values, of course) for more finegrained control over behavior.

Actor config will, of course, become more complicated, but this is an advanced feature in all cases.

**Comment by rkhamis** [comment] 2017-10-11 09:04
No, that won't work. Because a run has many actors. Which will conflict.

So it might be better to do it per AYS repo.

**Comment by rkhamis** [comment] 2017-10-11 09:07
Or input to the run create. It's the least invasive one and can be fine-tuned to give a lot of control over specific runs.

**Comment by zaibon** [comment] 2017-10-11 09:09
> No, that won't work. Because a run has many actors. Which will conflict.

Currently this is already the case. The run scheduler look for the lowest error level present in a run, and wait the time of this error level. This allow to retries as fast as the lowest error level allow you.

**Comment by alichaddad** [comment] 2017-10-11 13:54
I think it would be better if we specify the configuration during the run like this for example `ays run create --retriesConfig '20,10,10,20,10,10'` and make the default behavior configured using the `jumpscale9.toml`

**Comment by rkhamis** [comment] 2017-10-12 09:02
We have one of two options:

1. configure on actor level:
     - Each actor defines their own retries, possibly on specific actions even. (install retries slowly, start retries immediately, update never retries - for instance)
     - Scheduling the run will take the nearest retry of them and schedule the errored actions for it. But this raises three issues:
             - the finegrained control given to the user will not be met. It will depend on what other actors' actions are in that same run. This is undesirable because it would not be the expected behavior.
             - We'll have to consider that we might have to drop items (non-retriables) from said run. 
             - Slower retries might retry very fast, making them fail more times than needed.

2. configure on run level:
     - You can optionally define run retries while creating it. Number of retries and their period will be in the user's complete control.
     - Downside:
             - User has to be completely

**Comment by rkhamis** [comment] 2017-10-12 14:09
Let's stick to configuring the delays on the run. Behavior will be more predictable that way.

**Closed** 2017-11-07 09:50 UTC
Labels: state_verification, type_question
