### ISSUE TITLE
Add attribute to attach VM to external network

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#62] opened 2017-07-02 09:23 UTC
Related to https://github.com/Jumpscale/ays9/tree/master/templates/nodes/node.ovc

Allowing to create a VM that gets attached the external network of the VDC.

This was discussed/promised to the Artilium team building the e-portal.

**Comment by rkhamis** [comment] 2017-07-02 12:11
Part of https://github.com/Jumpscale/ays9/issues/64

**Comment by rkhamis** [comment] 2017-08-03 12:42
Duplicate of https://github.com/Jumpscale/ays9/issues/79

**Closed by rkhamis** 2017-08-03 12:42 UTC
Labels: priority_major, state_inprogress, type_feature
