### ISSUE TITLE
Unexpected error: Public JWT for issuer itsyouonline is not configured

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#413] opened 2018-01-22 12:43 UTC
#### Installation information

- jumpscale version: 9.2.1
- operating system: Ubuntu 1604

#### Detailed description

From the client logs, as provided by our partner:
```
2018-01-22 11:55:58.190 +00:00 [Information] [CockpitRequest] - 0HLB1DH27FJMM - {"Method":"GET","Url":"https://ays2.vreegoebezig.be/ays/repository/eYGP7uqEJwHjQlmusiZg/service/vdc/1Bek9pZVLkhwI3B3oIrj","Body":"{}"}

2018-01-22 11:56:03.375 +00:00 [Error] [CockpitResponse] - 0HLB1DH27FJMM - {"StatusCode":401,"Body":"\"Public JWT for issuer itsyouonline is not configured\""}
```

#### Steps to reproduce

When checking `jumpscale.log` using `tac jumpscale.log | grep -m 20 "StatusCode"`nothing found. Value for the `jwt_key` in `jumpscale.toml`  still was correct: `"MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAES5X8XrfKdx9gYayFITc89wad4usrk0n27MjiGYvqalizeSWTHEpnd7oea9IQ8T5oJjMVH5cc0H5tFSKilFFeh//wngxIyny66+Vq5t5B0V0Ehy01+2ceEon2Y0XDkIKv"`

**Comment by jelle-art** [comment] 2018-01-22 12:49
Steps to reproduce:
1. Create a VDC using a blueprint.
2. Request details of VDC:
Example:
Method:GET
Url:https://ays2.vreegoebezig.be/ays/repository/eYGP7uqEJwHjQlmusiZg/service/node/2sE3W8tNhtoThL9jtgsC
Body:{}

3. Response:
StatusCode:401
Body: Public JWT for issuer itsyouonline is not configured

**Comment by yveskerwyn** [comment] 2018-01-24 11:07
The problem is most probably because the url is wrong, it should be https://ays2.vreegoebezig.be/api/ays/repository/eYGP7uqEJwHjQlmusiZg/service/node/2sE3W8tNhtoThL9jtgsC instead

**Comment by yveskerwyn** [comment] 2018-01-24 11:08
this is because of the caddy config that was used in the setup:

caddy_cfg = """#tcpport:80

http://{0} {{
  redir https://{0}
}}

https://{0} {{
  proxy /api {1}:5000 {{
    without /api
    transparent
  }}

  proxy /apidocs {1}:5000 {{
    transparent
  }}
  
  proxy / {2}:8200 {{
    transparent
  }}
  
  gzip
  log
  tls {3}
}}
""".format(caddy_domain, internal_ip_address, portal_internal_ip_address, tls_email)

**Comment by rkhamis** [comment] 2018-01-24 11:19
I'll close this because it's a user-error

**Closed by rkhamis** 2018-01-24 11:19 UTC
Labels: priority_major, type_bug

**Comment by andrewayoub** [comment] 2018-01-24 12:40
## After investigations

this is not a valid url ```https://ays2.vreegoebezig.be/ays/repository/eYGP7uqEJwHjQlmusiZg/service/node/2sE3W8tNhtoThL9jtgsC``` 
it should be like ```{base_url}/api/ays/{requested_resource}``` 
so it should be  ```https://ays2.vreegoebezig.be/api/ays/repository/eYGP7uqEJwHjQlmusiZg/service/node/2sE3W8tNhtoThL9jtgsC```

@jelle-art , @yveskerwyn
