### ISSUE TITLE
AYS Portal > Service page showing 404 Client Error

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#120] opened 2017-07-19 15:53 UTC
#### Installation information

- jumpscale version: 9.0.3
- operating system: Ubuntu 16.04

#### Detailed description

See screenshot

#### Steps to reproduce

http://172.25.226.34:8200/AYS/Services?reponame=yves01

This is on ZeroTier network with 17d709436cdf03a2, ping me if you need access.

You'll also need to become a member of the artilium-dev organization on ItsYou.online.

#### Relevant stacktraces

![screen shot 2017-07-19 at 17 50 59](https://user-images.githubusercontent.com/13795109/28376564-bbb7ce7c-6caa-11e7-99f4-5a07e4c3709c.png)

**Comment by ahussein** [comment] 2017-07-28 15:42
The problem is with the account name 'Account of Yves' from the blueprint
`
g8client__cl:                                                                                                                                                                                               │····················
  url: 'be-gen-1.demo.greenitglobe.com'                                                                                                                                                                     │····················
  login: 'api_user'                                                                                                                                                                                         │····················
  password: '******'                                                                                                                                                                                      │····················
  account: 'Account of Yves'
`

It seems that our API cannot handle service names with spaces

**Comment by ahussein** [comment] 2017-07-28 17:44
can be reproduced in using the latest jumpscale from master via the following steps:

- Create new repo 
- Create new blueprint in the new repo with the following content:
```
g8client__client:
  url: 'be-gen-1.demo.greenitglobe.com'
  login: 'api_user'
  password: 'blabla'
  account: 'account of abdel'

vdc__vdctest1:
  g8client: 'client'
  location: 'be-gen-1'

actions:
 - action: install
```
- Execute the new blueprint
- Inside the repo directory execute the following command: ays service show -r account -n 'account for abdel'

**Comment by ahussein** [comment] 2017-07-31 13:43
https://github.com/Jumpscale/ays9/pull/131

**Comment by yveskerwyn** [comment] 2017-09-02 18:22
Does this also solve the problem as reported in https://github.com/Jumpscale/ays9/issues/206?

**Comment by ahussein** [comment] 2017-09-14 11:17
@yveskerwyn No, it will not solve the problem reported in #206, this fix will only fix the 504 Error that you get in the portal service page.
#206 is an open ticket so I will close this one since the error[504 in the portal service page] does not appear anymore

**Closed by ahussein** 2017-09-14 11:17 UTC
