### ISSUE TITLE
Stacktrace when running ays run list

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/ays9#243] opened 2017-09-13 09:30 UTC
#### Installation information

- jumpscale version: 9.1.2
- operating system: zero-os container

#### Detailed description
Stack trace found in ays logs after running ```ays run list```

#### Relevant stacktraces
```
Coroutine object created at (most recent call last):
  File "main.py", line 76, in <module>
    main()
  File "/opt/jumpscale9/lib/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/jumpscale9/lib/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/jumpscale9/lib/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/jumpscale9/lib/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 72, in main
    sanic_app.run(debug=debug, host=host, port=port, workers=1)
  File "/opt/jumpscale9/lib/sanic/app.py", line 595, in run
    serve(**server_settings)
  File "/opt/jumpscale9/lib/sanic/server.py", line 527, in serve
    loop.run_forever()
  File "/opt/jumpscale9/lib/asyncio/coroutines.py", line 121, in send
    return self.gen.send(value)
  File "/opt/jumpscale9/lib/sanic/app.py", line 503, in handle_request
    response = await response
  File "/opt/jumpscale9/lib/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/server/ays_if.py", line 63, in get
    return await auth(request, ays_api.listRuns(request, repository))
  File "/opt/jumpscale9/lib/asyncio/coroutines.py", line 80, in debug_wrapper
    return CoroWrapper(gen, None)
/opt/jumpscale9/lib/sre_parse.py:106: RuntimeWarning: coroutine 'listRuns' was never awaited
  self.pattern = pattern
```

**Comment by rkhamis** [comment] 2017-09-14 08:42
@FastGeert cannot reproduce on 9.1.2.... could you make sure that that is indeed the version?

**Comment by rkhamis** [comment] 2017-09-20 15:59
Fixed in https://github.com/Jumpscale/ays9/pull/265

**Comment by john-kheir** [comment] 2017-09-24 09:28
Verified

**Closed by john-kheir** 2017-09-24 09:28 UTC
Labels: state_verification
