### ISSUE TITLE
ovc.disk support for new disk performance tuning parameters

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays9#119] opened 2017-07-19 15:34 UTC
For Digital Energy (Russia) following was agreed:

In version 3.0 of G8 there will be support for the disk performance tuning parameters that were recently added to KVM. These parameters should be kept and managed at G8 OS level, e.g. so that migrating disk resources between the compute nodes preserves initially specified performance features. The full list of relevant parameters, that will be maintained at the end user Portal (but not visible / changeable by the User) and understood by the blueprint are:
a.       bps_max (throttling.bps-total-max): Total maximum (in bytes).
b.       bps_rd_max (throttling.bps-read-max): Read maximum.
c.       bps_wr_max (throttling.bps-write-max): Write maximum.
d.       iops_max (throttling.iops-total-max): Total maximum of I/O operations.
e.       iops_rd_max (throttling.iops-read-max): Read I/O operations.
f.        iops_wr_max (throttling.iops-write-max): Write I/O operations
g.       iops_total_max : bursts control
h.       iops_total_max_length : bursts control

This requires a OVC and/or Orchestrator API, but also an updated version of the ovc.disk template

**Comment by rkhamis** [comment] 2017-09-06 15:17
Duplicate of #187

**Closed by rkhamis** 2017-09-06 15:17 UTC
Labels: type_feature
